---
- hosts: debian
  tasks:
    - name: "sudo apt install java 11"
      apt:
        name: openjdk-11-jdk
        state: latest
      become: yes

    - name: "copy jar"
      copy:
        src: /var/lib/jenkins/workspace/ayaskevich/freestyle-job/target/smart-home-1.0-SNAPSHOT.jar
        dest: ayaskevich/smart-home.jar

    - name: "copy conf file"
      copy:
        src: /var/lib/jenkins/workspace/ayaskevich/freestyle-job/smart-home-1.js
        dest: ayaskevich/smart-home-1.js
