---
- hosts: debian
  tasks:
    - name: "sudo apt install java 11"
      apt:
        name: openjdk-11-jdk
        state: latest
      become: yes

    - name: "copy jar"
      copy:
        src: ../target/smart-home-1.0-SNAPSHOT.jar
        dest: smart-home.jar
        remote_src: yes

    - name: "copy conf file"
      copy:
        src: ../smart-home-1.js
        dest: smart-home-1.js

    - name: "launch java app"
      shell: java -jar smart-home.jar
